import { json, type LoaderFunctionArgs, type LinksFunction, type MetaFunction } from "@remix-run/node";
import { useLoaderData } from "@remix-run/react";
import db from "~/lib/db.server";
import { requireStaff } from "~/lib/session.server";
import { hospitalSettings } from "~/lib/settings.server";
import { age, dateTime } from "~/lib/format";
import printStyles from "~/styles/print.css?url";

export const links: LinksFunction = () => [{ rel: "stylesheet", href: printStyles }];
export const meta: MetaFunction = () => [{ title: "Lab report · Lumora" }];

export async function loader({ request, params }: LoaderFunctionArgs) {
  await requireStaff(request);
  const o = db.prepare(`SELECT o.*, p.full_name AS patient, p.mrn, p.gender, p.birth_date, p.blood_group, e.id AS enc,
      st.full_name AS doctor, st.title AS doctor_title, d.name AS dept
    FROM orders o JOIN encounters e ON e.id=o.encounter_id JOIN patients p ON p.id=e.patient_id
    LEFT JOIN staff st ON st.id=o.ordered_by LEFT JOIN departments d ON d.id=st.department_id WHERE o.id=?`).get(params.orderId) as any;
  if (!o) throw new Response("Not found", { status: 404 });
  const results = db.prepare("SELECT analyte, value, unit, ref_range, flag FROM lab_results WHERE order_id=? ORDER BY id").all(o.id) as any[];
  return json({ o, results, hospital: hospitalSettings() });
}

const FL: Record<string, string> = { high: "fl-high", low: "fl-low", critical: "fl-critical" };

export default function Report() {
  const { o, results, hospital } = useLoaderData<typeof loader>();
  const abnormal = results.filter((r: any) => r.flag && r.flag !== "normal");
  return (
    <div className="doc-screen">
      <div className="print-actions no-print">
        <a href={`/workspace`} className="btn">← Back</a>
        <button className="btn primary" onClick={() => window.print()}>Print / Save PDF</button>
      </div>
      <div className="doc">
        <div className="doc-head">
          <div className="doc-brand">
            <img src="/logo.svg" alt="" />
            <div><b>{hospital.name}</b><span>{hospital.accreditation} · {hospital.tagline}</span></div>
          </div>
          <div className="meta">
            <div>Report #{o.id.slice(-8).toUpperCase()}</div>
            <div>Issued {dateTime(o.resulted_at ?? o.created_at)}</div>
          </div>
        </div>

        <div className="doc-title">Laboratory Report</div>
        <div className="doc-grid">
          <div><span className="k">Patient</span><div className="v">{o.patient}</div></div>
          <div><span className="k">MRN</span><div className="v">{o.mrn}</div></div>
          <div><span className="k">Age / Sex</span><div className="v">{age(o.birth_date)} · {o.gender ?? "—"}</div></div>
          <div><span className="k">Blood group</span><div className="v">{o.blood_group ?? "—"}</div></div>
          <div><span className="k">Requested by</span><div className="v">{o.doctor ?? "—"}{o.dept ? ` · ${o.dept}` : ""}</div></div>
          <div><span className="k">Panel</span><div className="v">{o.name}</div></div>
        </div>

        <table className="doc-tbl">
          <thead><tr><th>Analyte</th><th style={{ textAlign: "right" }}>Result</th><th>Unit</th><th>Reference</th><th>Flag</th></tr></thead>
          <tbody>
            {results.map((rr: any, i: number) => (
              <tr key={i}>
                <td>{rr.analyte}</td>
                <td className={`num ${FL[rr.flag] ?? ""}`}>{rr.value}</td>
                <td>{rr.unit}</td>
                <td style={{ color: "#64748b", fontFamily: "IBM Plex Mono, monospace" }}>{rr.ref_range}</td>
                <td className={FL[rr.flag] ?? ""}>{rr.flag && rr.flag !== "normal" ? rr.flag.toUpperCase() : "—"}</td>
              </tr>
            ))}
            {results.length === 0 && <tr><td colSpan={5} style={{ color: "#94a3b8" }}>Results pending.</td></tr>}
          </tbody>
        </table>

        <div className="doc-note">
          <b>Interpretation:</b> {abnormal.length === 0
            ? "All measured parameters are within their reference ranges."
            : `${abnormal.length} parameter(s) outside reference range: ${abnormal.map((a: any) => a.analyte).join(", ")}. Correlate clinically.`}
        </div>

        <div className="doc-sign">
          <div className="line">Verified by Central Laboratory</div>
          <div className="line" style={{ textAlign: "right" }}>{o.doctor ?? "Attending Physician"}<br /><span style={{ fontSize: 11 }}>{o.doctor_title ?? ""}</span></div>
        </div>
        <div className="doc-foot">This report was generated by Lumora Hospital Operating System. For queries contact the Central Laboratory. Not valid without verification.</div>
      </div>
    </div>
  );
}
